### ISSUE TITLE
[Question]: Testing EventListener implementations.

### ISSUE THREAD

**Issue by phillipbaird** [disintegrate-es/disintegrate#109]
Firstly, thank you for sharing the Disintegrate project.  I am currently experimenting with it in side project.

I am wondering how other folks are testing EventListener implementations?

In my case I've got an EventListener maintaining a projection for my read model.  In an ideal world I'd like to be able to test this with Given-When-Then styles tests, i.e. Given past events G, When new events W are processed by the event listener, Then I expect the read model to have state T.

The [it_handles_events](https://github.com/disintegrate-es/disintegrate/blob/e52135cac1c3947259666aef226f420e19e9e7e0/disintegrate-postgres/src/listener/tests.rs#L128) test for PgEventListener is a sqlx::test similar to what I'm envisaging.  The obstacle being that it relies on access to the PgEventListenerExecutor which is not public.

Is there another/better way of doing this?

**Comment by luca-iachini** [comment]
Hey @phillipbaird, 

Thanks a lot for trying Disintegrate out. We appreciate that and we would like to hear your feedback on the library.

This is a good question, and we realized that we are not providing good examples of how to test an `EventListener` for read models. 

We did not expose `PgEventListenerExecutor` because it is an internal component, and we would like to be able to change it without breaking the user code.  We believe that if users follow the next strategies, they can reach a good test suite for their read models. 

There are multiple ways to implement a read model using Disintegrate, and it depends on the application's design. We’ll provide a couple of examples.

In a hexagonal architecture, we could:
Define the read model in our domain. Using the classical bank example:

```rust
#[derive(Default, Clone, Eq, PartialEq)]
struct AccountBalance {
    id: Uuid, // your accountId value type
    amount: i64, // your value type
}
```

Implement an update method for our read models. For example defining a `ReadModel` trait:

```rust
trait ReadModel<E> {
    fn update(&mut self, event: E);
}

impl ReadModel<DomainEvent> for AccountBalance {
    fn update(&mut self, event: DomainEvent) {
        match event {
            DomainEvent::Deposit { amount, .. } => {
                self.amount += amount;
            }
            DomainEvent::Withdraw { amount, .. } => {
                self.amount -= amount;
            }
            // other events
        }
    }
}
```

Using a TDD approach, we could write tests like the following first and then implement our read model:

```rust
#[test]
fn it_handles_deposit_events() {
    // given
    let mut read_model = AccountBalance::default();
    
    // when
    read_model.update(DomainEvent::Deposit { amount: 10 });
    
    // then
    assert_eq!(read_model.amount, 10);
}

#[test]
fn it_handles_withdraw_events() {
    // given
    let mut read_model = AccountBalance { amount: 10 };
    
    // when
    read_model.update(DomainEvent::Withdraw { amount: 10 });
    
    // then
    assert_eq!(read_model.amount, 0);
}
```

Implement the PostgreSQL Repository in our infrastructure (this is a simplified version):

```rust
struct PgAccountBalanceRepository {
    pool: PgPool, 
}

impl PgAccountBalanceRepository {
    async fn by_id(&self, id: Uuid) -> Result<AccountBalance, sqlx::Error> {
        Ok(sqlx::query!(..).fetch_one(&self.pool).await?.unwrap_or_default())
    }

    async fn store(&self, account_balance: AccountBalance) -> Result<(), sqlx::Error> {
        sqlx::query!(..).bind(..).execute(&self.pool).await?;
        Ok(())
    }
} 

#[async_trait]
impl EventListener<DomainEvent> for PgAccountBalanceRepository {
    type Error = sqlx::Error;

    fn id(&self) -> &'static str {
        "balance"
    }

    fn query(&self) -> &StreamQuery<DomainEvent> {
        query!()
    }

    async fn handle(&self, event: PersistedEvent<DomainEvent>) -> Result<(), Self::Error> {
        let event = event.into_inner();
        let mut read_model = self.by_id(event.account_id()).await?;
        read_model.update(event);
        self.store(read_model).await?;
        Ok(())
    }
}
```

In a TDD approach, here we need to test the `by_id` and `store`:

```rust
#[sqlx::test(fixtures = "balances")]
async fn it_loads_by_id(pool: PgPool) {
    let repo = PgAccountBalanceRepository { pool };
    let result = repo.by_id(uuid!("id")).await.unwrap();
    assert_eq!(AccountBalance { id: uuid!("id"), amount: 10 }, result);
}

#[sqlx::test]
async fn it_stores_an_account(pool: PgPool) {
    let repo = PgAccountBalanceRepository { pool };
    let result = repo.store(AccountBalance { id: uuid!(""), amount: 10 }).await.unwrap();
    // sqlx query to check the stored account
}
```

Then I think you covered it all. If you want to add one more test on `EventListener::handle` it is doable, to check if the `by_id`, `update` and `store` are called in the `EventListener` implementation.

This approach has the advantage of separating the domain from the infrastructure implementation but it has the cost of one read and one store per event.

Another way is to implement everything in the event handler directly, having one update or insert per event. You can check this implementation [here](https://github.com/disintegrate-es/disintegrate/blob/main/examples/courses/src/read_model.rs).

Then, we can write a test for each event, like:

```rust
#[sqlx::test(fixture = "accounts")]
async fn it_handles_deposit(pool: PgPool) {
    let listener = PgAccountBalanceEventListener { pool };
    let result = listener.handle(PersistedEvent::new(1, DomainEvent::Deposit { id: uuid!(""), amount: 10 })).await.unwrap();
    // sqlx query to check the stored account has been updated
}
```

This should already cover all from the user perspective.

Let us know if this is what you mean or if you have different tests in mind. If there is a design flaw that we can improve, we are welcome to hear your opinions on that.

**Comment by phillipbaird** [comment]
Hi @luca-iachini,

Thank you for such a comprehensive answer.
It has answered all my queries.
